feat(page: right-control): completed todo item can be hide
NG-ZORRO/today-ng-steps pull request #4
Opened 2018-09-15 13:22 UTC by tirelyl

2018-09-15 13:37 UTC, tirelyl commented
[https://tirelyl.github.io/today-ng-steps](online demo)

2018-09-15 13:38 UTC, tirelyl commented
online demo[https://tirelyl.github.io/today-ng-steps](url)

2018-09-15 13:38 UTC, tirelyl commented
https://tirelyl.github.io/today-ng-steps  online demo

2018-09-15 13:41 UTC, wzhudev requested changes

2018-09-15 13:41 UTC, wendzhue commented on src/app/pages/main/right-control/header/header.component.html
> +          {{ completedHide ? '显示以完成' : '隐藏已完成' }}
错别字

2018-09-15 13:41 UTC, wendzhue commented on src/app/pages/main/right-control/header/header.component.html
> +        更多设置
叫设置就可以了
最好设置 icon

2018-09-15 13:43 UTC, wendzhue commented on src/app/pages/main/right-control/todo/todo.component.html
> +    <nz-list-item *ngIf="!(item.completedFlag && completedHide)" class="todo-item" (click)="click(item._id)" (contextmenu)="contextMenu($event, todoContextRef, item._id)">
这样的代码把决定该显示什么东西的算法分离到模板当中, 但是更多的算法在组建类里, 这样会造成后续不易维护.

2018-09-16 02:51 UTC, wzhudev approved these changes

2018-09-16 02:52 UTC, merged